### ISSUE TITLE
вот просто зачем

### ISSUE THREAD

**Issue by andrei-valikov** [tandav/chans#2]
это мусор, это дно психики
разве нет мечты о гармонии о счастье о спокойствии
когда жизнь простая
когда всё понятно из момента здесь и сейчас
разве ты полностью себя ассоциируешь с этим мусором
живу в жопе давай тогда и обустроюсь там основательно

**Comment by andrei-valikov** [comment]
свити фокс слили
масштаб мышления понятен

**Comment by tandav** [comment]
@andrei-valikov https://www.youtube.com/watch?v=FpZhZK_LzrU
